export const cardData = [
  {
    status: 'Ongoing',
    title: 'Finished',
    desc: 'ITR Filing',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Ongoing',
    title: 'Finished',
    desc: 'Company Registration',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Ongoing',
    title: 'Finished',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Ongoing',
    title: 'Finished',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Ongoing',
    title: 'Finished',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Ongoing',
    title: 'Finished',
    desc: 'ITR Filing',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Old',
    title: 'Pending',
    desc: 'Company Registration',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Old',
    title: 'Pending',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Old',
    title: 'Pending',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Old',
    title: 'Finished',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text ',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Old',
    title: 'Finished',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
  {
    status: 'Old',
    title: 'Finished',
    desc: 'Lorem Ipsum has been the industrys',
    ApplicationDate: '12-03-2023',
    ApplicationStatus: 'OnGoing',
    Name: 'Simply dummy text',
    Email: 'Simply dummy text',
    Contact: 'Simply dummy text',
    Address: 'Simply dummy text',
    ServiceType: 'ITR Filing',
    Payment: 'Pending',
  },
]
